const INIT_APP = 'INIT_APP';

const PAGE_END = 'PAGE_END';
const PAGE_ERROR = 'PAGE_ERROR';
const PAGE_FETCH = 'PAGE_FETCH';
const PAGE_NAVIGATE = 'PAGE_NAVIGATE';

export {
    INIT_APP,
    
    PAGE_END,
    PAGE_ERROR,
    PAGE_FETCH,
    PAGE_NAVIGATE,
};
