const INIT_APP = 'INIT_APP';

const CHAT_END_MESSAGE = 'CHAT_END_MESSAGE';
const CHAT_END_USER = 'CHAT_END_USER';
const CHAT_INIT = 'CHAT_INIT';
const CHAT_FETCH_MESSAGE = 'CHAT_FETCH_MESSAGE';
const CHAT_FETCH_USER = 'CHAT_FETCH_USER';

const PAGE_END = 'PAGE_END';
const PAGE_ERROR = 'PAGE_ERROR';
const PAGE_FETCH = 'PAGE_FETCH';
const PAGE_NAVIGATE = 'PAGE_NAVIGATE';

export {
    INIT_APP,
    
    CHAT_END_MESSAGE,
    CHAT_END_USER,
    CHAT_INIT,
    CHAT_FETCH_MESSAGE,
    CHAT_FETCH_USER,

    PAGE_END,
    PAGE_ERROR,
    PAGE_FETCH,
    PAGE_NAVIGATE,
};
