const INIT_APP = 'INIT_APP';

const CHAT_INIT = 'CHAT_INIT';
const CHAT_MESSAGE_END = 'CHAT_MESSAGE_END';
const CHAT_MESSAGE_START = 'CHAT_MESSAGE_START';
const CHAT_SEND = 'CHAT_SEND';
const CHAT_TYPING_END = 'CHAT_TYPING_END';
const CHAT_TYPING_START = 'CHAT_TYPING_START';
const CHAT_USER_END = 'CHAT_USER_END';
const CHAT_USER_START = 'CHAT_USER_START';

const CHESS_INIT = 'CHESS_INIT';

const PAGE_END = 'PAGE_END';
const PAGE_ERROR = 'PAGE_ERROR';
const PAGE_FETCH = 'PAGE_FETCH';
const PAGE_NAVIGATE = 'PAGE_NAVIGATE';

export {
    INIT_APP,
    
    CHAT_INIT,
    CHAT_MESSAGE_END,
    CHAT_MESSAGE_START,
    CHAT_SEND,
    CHAT_TYPING_END,
    CHAT_TYPING_START,
    CHAT_USER_END,
    CHAT_USER_START,

    CHESS_INIT,

    PAGE_END,
    PAGE_ERROR,
    PAGE_FETCH,
    PAGE_NAVIGATE,
};
